### PR TITLE
Update to Spring Boot 1.3.1.RELEASE

### PR DESCRIPTION
**Pull request by joshiste**
This updates spring-boot-starter-batch-web to Spring Boot 1.3.1.
This PR contains several commits:
1. (a37190a) To do a clean successful build  I had to correct some invalid javadoc
2. (9c3371d) For metrics the code relied on MetricRepository. But we needed just to read values here. With this commit the MetricReader-interface is used. This is also due to the fact that Spring Boot 1.3. doesn't create a MetricRepository for Java 8.
3. (5c5c346) As discussed with @denschu, I removed the Metrics-Exporters and the dependency to codahale-metrics, 'cause it ain't nothing to do with batches. The metric exporters are still triggered on job finish.
3. (55c8294) This is the version upgrade to boot 1.3.1.

### CODE REVIEW

**Comment by joshiste** [comment]
There seems to be an issue on java 7 with 2 MetricReader beans being available. I need to investigate further... *sigh*

**Comment by joshiste** [comment]
@denschu I am done with my changes an tested this with [spring-samples/batch-boot-simple](https://github.com/codecentric/spring-samples/tree/master/batch-boot-simple)

**Comment by joshiste** [comment]
@denschu @tobiasflohre is there any schedule for releasing this?

**Comment by tobiasflohre** [comment]
We could merge your other PR and do a 1.4.0 Release, what do you think, @denschu?

**Pull request merged**
